### ISSUE TITLE
Can We check Pairing Status

### ISSUE THREAD

**Issue by rohitsangwan01** [coral/freemote#1]
Hey , nice work , 
After Sending Pair request to camera , is there any way to detect if users accepts that pairing request in camera , or canceled that
or in case if we want to check the pairing status with camera . ( i know we can check if camera if in Pairing mode , or enabled from manufacturer data )

**Comment by coral** [comment]
@rohitsangwan01 

The TAG data is a bitmask.

PairingSupported | 0x80
PairingEnabled | 0x40
LocationFunctionSupported | 0x20
LocationFunctionEnabled | 0x10
UnknownFunctionSupported | 0x08
UnknownFunctionEnabled | 0x04
RemoteFunctionEnabled | 0x02
Unknown | 0x01

this means you can use the 0x22 tag, bitmask using these to figure out what state the camera is in. If the camera advertises 0x40 it's open for pairing. 

https://github.com/coral/freemote/blob/933b97d4dce69a1c5ab54421bcfebb6b438b2546/src/BLECamera.cpp#L229

You can see how I use it here.

**Comment by rohitsangwan01** [comment]
@coral yes but this tag data can only tell us if camera is pairable or not , but after connecting camera will not advertise

so first i am connecting to camera
and then sending Pairing command 

and pair dialog popup in camera
but this is just one time process

now what i want to check is , if that camera is already paired with my device

either we need to getBonded devices list from platform , 

but is there any way to confirm it from camera programatically

**Comment by coral** [comment]
@rohitsangwan01 no you just connect and listen, if the camera starts spamming you updates on the ble services you can assume that it's bonded otherwise it never sends anything.

at least that's how I remembered it.

If you want to know what devices the NRF527840 device has bound to you can use LittleFS and just explore the saved keys and compare MAC addresses but I never got that far since this worked.

**Comment by rohitsangwan01** [comment]
@coral ok great , thank you
